
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pet2Share_API.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Album
{

    public Album()
    {

        this.Post_Uploads = new HashSet<Post_Upload>();

    }


    public int ID { get; set; }

    public string Name { get; set; }

    public int PersonID { get; set; }

    public System.DateTime DateAdded { get; set; }

    public System.DateTime DateModified { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }



    public virtual Person Person { get; set; }

    public virtual ICollection<Post_Upload> Post_Uploads { get; set; }

}

}
