//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet2Share_API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Albums = new HashSet<Album>();
            this.PostLikes = new HashSet<PostLike>();
            this.Users = new HashSet<User>();
            this.Posts = new HashSet<Post>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string AlternateEmail { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string PrimaryPhone { get; set; }
        public string SecondaryPhone { get; set; }
        public string Avatar { get; set; }
        public string AboutMe { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string CoverPicture { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Album> Albums { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<PostLike> PostLikes { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
    }
}
