//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet2Share_API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetType
    {
        public PetType()
        {
            this.BreedTypes = new HashSet<BreedType>();
            this.PetProfiles = new HashSet<PetProfile>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<BreedType> BreedTypes { get; set; }
        public virtual ICollection<PetProfile> PetProfiles { get; set; }
    }
}
