//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet2Share_API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post_Upload
    {
        public int ID { get; set; }
        public int PostID { get; set; }
        public string UploadedFilePath { get; set; }
        public string FileMimeType { get; set; }
        public string FileExtension { get; set; }
        public Nullable<int> AlbumID { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateModified { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Post Post { get; set; }
    }
}
