//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet2Share_API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.People = new HashSet<Person>();
            this.PetProfiles = new HashSet<PetProfile>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public byte[] Password { get; set; }
        public int PrimaryPersonId { get; set; }
        public string Email { get; set; }
        public string AlternateEmail { get; set; }
        public string Phone { get; set; }
        public Nullable<int> SocialMediaSourceId { get; set; }
        public string SocialMediaUsername { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<PetProfile> PetProfiles { get; set; }
        public virtual SocialMediaSource SocialMediaSource { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
